version: '3'
services:
  api:
    build:
      context: ./api/
    command: "node app.js"
    restart: always
    environment:
      NODE_ENV: production

  # nginx:
  #   build:
  #     context: ./client/
  #     dockerfile: Dockerfile-prod
  #   ports:
  #     - "80:80"
  #   restart: always
  #   # env_file: ./nginx/.env # TODO - uncomment this to auto-load your .env file!
  #   depends_on:
  #     - api
