version: '3.8'

services:
  api:
    env_file:
      "./.env"
    build:
      dockerfile: "./Dockerfile"
      context: "./"
    ports:
      - "5000:5000"
    networks:
      - webappnetwork

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - webappnetwork

networks:
    webappnetwork:
        driver: bridge
